apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: anurodh1/gitops:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  type: NodePort
  selector:
    app: reactapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
